services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - TROPIC_API_HOST=0.0.0.0
      - TROPIC_DATABASE_URL=mongodb://mongo:27017
    networks:
      - app-nginx
      - app-mongo
    depends_on:
      - mongo
    expose:
      - "8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 10s
      timeout: 5s
      retries: 3

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - app-nginx

  mongo:
    restart: unless-stopped
    image: mongo:8-noble
    volumes:
      - mongo_data:/data/db
    networks:
      - app-mongo
    expose:
      - 27017

networks:
  app-nginx:
  app-mongo:

volumes:
  mongo_data:
