from typing import Any

raw_data: list[dict[str, Any]] = [
    {
        "monomer_smiles": "CC1CCCC(=O)O1",
        "initiator_smiles": "OCc1ccccc1",
        "product": {
            "number_of_units": 1.0,
        },
        "is_experimental": True,
        "parameters": {
            "temperature": None,
            "pressure": None,
            "solvent": None,
            "solvent_conc": None,
            "monomer_state": "l",
            "polymer_state": "a",
            "method": None,
            "solvent_model": None,
            "functional": None,
            "basis_set": None,
            "dispersion": None,
            "forcefield": None,
        },
        "thermo": {
            "delta_h": -19.3,
            "delta_s": -62.0,
            "ceiling_temperature": None,
        },
        "comment": None,
        "doi": None,
        "url": None,
    },
    {
        "monomer_smiles": "CCC1CCCC(=O)O1",
        "initiator_smiles": "OCc1ccccc1",
        "product": {
            "number_of_units": 1.0,
        },
        "is_experimental": True,
        "parameters": {
            "temperature": None,
            "pressure": None,
            "solvent": None,
            "solvent_conc": None,
            "monomer_state": "l",
            "polymer_state": "a",
            "method": None,
            "solvent_model": None,
            "functional": None,
            "basis_set": None,
            "dispersion": None,
            "forcefield": None,
        },
        "thermo": {
            "delta_h": -16.4,
            "delta_s": -55.0,
            "ceiling_temperature": None,
        },
        "comment": None,
        "doi": None,
        "url": None,
    },
    {
        "monomer_smiles": "CC1CCCC(=O)O1",
        "initiator_smiles": "OCc1ccccc1",
        "product": {
            "number_of_units": 1.0,
        },
        "is_experimental": True,
        "parameters": {
            "temperature": None,
            "pressure": None,
            "solvent": None,
            "solvent_conc": None,
            "monomer_state": "s",
            "polymer_state": "s",
            "method": None,
            "solvent_model": None,
            "functional": None,
            "basis_set": None,
            "dispersion": None,
            "forcefield": None,
        },
        "thermo": {
            "delta_h": -13.8,
            "delta_s": -41.2,
            "ceiling_temperature": None,
        },
        "comment": None,
        "doi": None,
        "url": None,
    },
]
